
[general]
	#Puts all the added items into a new Every Compat tab instead of their own mod tabs. Be warned that if disabled it could cause some issue with some mods that have custom tabs
	creative_tab = true
	#Makes dynamic assets that are generated depend on loaded resource packs. Turn off to make them just use vanilla assets
	assets_depend_on_loaded_packs = true
	#Creates a debug folder inside your instance directory where all the dynamically generated resources will be saved
	save_debug_resources = false
	#Sends a packet to verify all dependencies mod versions are the same on connect. DIsable if it causes issues
	mod_version_check_packet = true
	#Don't touch unless you are told to
	debug_packet = false

	[general.tooltips]
		#Enabled tooltips showing which mod an EC item is from
		mod_origin_enabled = true
		#Enabled tooltips showing which block type an EC item is made from
		block_type_enabled = true
		#Only show on advanced settings
		show_on_advanced_tooltips = false

	#Disables certain types
	[general.types]

		[general.types.wood_type]

			[general.types.wood_type.ars_nouveau]
				archwood = true

			[general.types.wood_type.rats]
				pirat = true

			[general.types.wood_type.quark]
				azalea = true
				ancient = true
				blossom = true

			[general.types.wood_type.aether]
				skyroot = true

			[general.types.wood_type.undergarden]
				smogstem = true
				wigglewood = true
				grongle = true

			[general.types.wood_type.spawn]
				rotten = true

			[general.types.wood_type.deep_aether]
				roseroot = true
				yagroot = true
				cruderoot = true
				conberry = true
				sunroot = true

			[general.types.wood_type.enlightened_end]
				indigo = true
				cerulean = true

			[general.types.wood_type.alexscaves]
				pewen = true
				thornwood = true

		[general.types.leaves_type]

			[general.types.leaves_type.ars_nouveau]
				blue_archwood = true
				green_archwood = true
				purple_archwood = true
				red_archwood = true

			[general.types.leaves_type.aether]
				skyroot = true
				golden_oak = true
				crystal = true
				crystal_fruit = true
				holiday = true
				decorated_holiday = true

			[general.types.leaves_type.vinery]
				grapevine = true
				dark_cherry = true
				apple = true

			[general.types.leaves_type.undergarden]
				smogstem = true
				wigglewood = true
				grongle = true

			[general.types.leaves_type.rats]
				pirat = true

			[general.types.leaves_type.quark]
				ancient = true
				blue_blossom = true
				lavender_blossom = true
				orange_blossom = true
				yellow_blossom = true
				red_blossom = true

			[general.types.leaves_type.deep_aether]
				roseroot = true
				flowering_roseroot = true
				blue_roseroot = true
				flowering_blue_roseroot = true
				yagroot = true
				cruderoot = true
				conberry = true
				sunroot = true

			[general.types.leaves_type.alexscaves]
				ancient = true

	#Disables specific entries
	[general.entries]

		[general.entries.wood_type]

			[general.entries.wood_type.storagedrawers]
				full_drawers_2 = true
				half_drawers_1 = true
				full_drawers_4 = true
				half_drawers_4 = true
				trim = true
				half_drawers_2 = true
				full_drawers_1 = true

			[general.entries.wood_type.quark]
				vertical_planks = true
				post = true
				trapped_chest = true
				bookshelf = true
				chest = true
				stripped_post = true
				ladder = true
				hollow_log = true

			[general.entries.wood_type.twigs]
				table = true

			[general.entries.wood_type.farmersdelight]
				cabinet = true

		[general.entries.leaves_type]

			[general.entries.leaves_type.quark]
				hedge = true
				leaf_carpet = true

